/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Add a repository to the registry by absolute local path.
	 * 
	 *  Thin wrapper over [`reposync_core::repo::add`]: validates + inspects + writes
	 *  the `repos` / `repo_local_state` rows and returns the new [`RepoId`].
	 */
	repoAddPath: (path: string) => typedError<RepoId, AppErrorPayload>(__TAURI_INVOKE("repo_add_path", { path })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Run a "check now" for a tracked repo, then broadcast the result.
	 * 
	 *  Calls [`reposync_core::repo::check_now`], emits the `repo:check-completed`
	 *  event so every window's listener sees the outcome, and returns the full
	 *  [`CheckResult`] to the caller.
	 */
	repoCheckNow: (id: number) => typedError<CheckResult, AppErrorPayload>(__TAURI_INVOKE("repo_check_now", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Run a "check now" over every ENABLED repo (E-13 tray "Check All Now").
	 * 
	 *  The additive E-13 backend command behind the tray "Check All Now" item (also
	 *  callable from the frontend). Selects the enabled repos (the pure
	 *  [`reposync_core::store::select_check_all_targets`]) and runs each through the
	 *  SAME per-repo lock the scheduler uses, so a tray check-all and a scheduled check
	 *  never launch two `git` processes in one working tree. Returns the number of repos
	 *  checked. Per-repo events fire like a manual check (`check-started` /
	 *  `check-completed`); a per-repo failure is surfaced via `error:raised` (the tray
	 *  action is fire-and-forget, so there is no synchronous caller to receive it) and
	 *  does not abort the run.
	 * 
	 *  Since BL-NI-04 the returned count means "attempted", not "succeeded". A check
	 *  whose fetch failed now returns `Ok` with `failed: true`, so it emits its
	 *  completion event and counts here. That widening is deliberate and it is the
	 *  honest reading of a tray item labelled "Check All Now": the user asked for N
	 *  repos to be checked, N were checked, and some of them came back with bad news
	 *  that the per-repo event now carries. The `error:raised` arm is left for the
	 *  checks that could not RUN at all.
	 */
	repoCheckAll: () => typedError<number, AppErrorPayload>(__TAURI_INVOKE("repo_check_all")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  List tracked repos (summary view), filtered. */
	repoList: (filter: RepoFilter) => typedError<RepoSummary[], AppErrorPayload>(__TAURI_INVOKE("repo_list", { filter })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Get the full detail of a single tracked repo. */
	repoGet: (id: number) => typedError<RepoDetail, AppErrorPayload>(__TAURI_INVOKE("repo_get", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Scan a parent folder for candidate git repositories. */
	repoScanParent: (path: string) => typedError<ScanResult, AppErrorPayload>(__TAURI_INVOKE("repo_scan_parent", { path })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Remove a tracked repo (does not touch the working tree). */
	repoRemove: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_remove", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Enable or disable scheduled checks for a repo. */
	repoSetEnabled: (id: number, enabled: boolean) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_set_enabled", { id, enabled })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Set the per-repo update policy (E-07).
	 * 
	 *  Thin wrapper over [`reposync_core::store::repo_set_policy`]: persists the
	 *  repo's `update_mode`, rejecting a non-V1 mode at the boundary.
	 */
	repoSetPolicy: (id: number, policy: UpdatePolicy) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_set_policy", { id, policy })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Set a repo's per-repo check cadence (BL-NI-30 / finding 15).
	 * 
	 *  Additive E-06 amendment (a new command, not a change to `repo_set_policy`, which
	 *  carries only mode + dirty-handling). `checkFrequencyMin` follows the inherit
	 *  model: `0` inherits the global cadence (`settings.global_check_minutes`), a
	 *  POSITIVE value is an explicit per-repo override in minutes. Persists the new
	 *  cadence via the store, then recomputes this repo's `next_check_at` with the SAME
	 *  anchored rule the global-cadence change uses
	 *  ([`reposync_core::scheduler::reschedule_one_repo`]), so a shorter override - or a
	 *  switch back to inherit - takes effect immediately instead of waiting out the
	 *  stale schedule. A negative value is rejected (`InvalidSetting`); a missing repo
	 *  is `NotFound`.
	 */
	repoSetCadence: (id: number, checkFrequencyMin: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_set_cadence", { id, checkFrequencyMin })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Run an "update now" for a repo in the given mode (E-07).
	 * 
	 *  Emits `repo:update-started` before the run, calls the shared
	 *  [`reposync_core::repo::update_now`] decide -> execute -> record path (the same
	 *  path the E-08 scheduler reuses), then emits `repo:update-completed` with the
	 *  outcome and returns the full [`UpdateResult`].
	 */
	repoUpdateNow: (id: number, mode: UpdateMode) => typedError<UpdateResult, AppErrorPayload>(__TAURI_INVOKE("repo_update_now", { id, mode })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Refresh GitHub / remote metadata for a repo, then return the updated detail.
	 * 
	 *  Thin edge over [`reposync_core::github::refresh_one`] on the unauthenticated V1 path
	 *  (`NoToken`): fetch + persist, map any engine failure to an [`AppError`]
	 *  ([`refresh_report_error`]), then re-read the [`RepoDetail`]. A MANUAL refresh fetches
	 *  unconditionally, so the deferred release-cadence caveat (BL-NI-15b) does not apply.
	 */
	repoRefreshMetadata: (id: number) => typedError<RepoDetail, AppErrorPayload>(__TAURI_INVOKE("repo_refresh_metadata", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Open the repo's folder in the OS file manager. */
	repoOpenFolder: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_open_folder", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Open the repo in a terminal. */
	repoOpenTerminal: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_open_terminal", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Open the repo in the configured editor. */
	repoOpenEditor: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_open_editor", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Open the repo's remote (origin URL) in the browser. */
	repoOpenRemote: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("repo_open_remote", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  List activity-log records, filtered (newest first).
	 * 
	 *  Thin wrapper over [`reposync_core::activity::list`]: the read-side counterpart
	 *  to the E-09 writer, returning the filtered audit trail for the activity-timeline
	 *  UI. The core clamps the row limit so a UI read can never pull the whole log.
	 */
	activityList: (filter: ActivityFilter) => typedError<ActivityRecord[], AppErrorPayload>(__TAURI_INVOKE("activity_list", { filter })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Get today's daily summary (for the user's local day).
	 * 
	 *  Thin wrapper over [`reposync_core::summary::summary_today`]: the edge supplies the
	 *  local-day window ([`crate::localtime::local_day_window`]) because reposync-core is
	 *  timezone-free, then the core aggregates the day's activity + state read-only.
	 */
	summaryToday: () => typedError<DailySummary, AppErrorPayload>(__TAURI_INVOKE("summary_today")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Get the current week's summary (V1.1 stub). */
	summaryWeek: () => typedError<WeeklySummary, AppErrorPayload>(__TAURI_INVOKE("summary_week")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Read the settings singleton. */
	settingsGet: () => typedError<Settings, AppErrorPayload>(__TAURI_INVOKE("settings_get")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Write the settings singleton. */
	settingsSet: (settings: Settings) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("settings_set", { settings })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Read the one-time database-recovery notice (E-02 AC7 / BL-NI-33).
	 * 
	 *  Additive E-06 amendment. Surfaces the `db_recovered` / `db_backup_path` fields
	 *  parked in [`AppState`] after a startup migration-failure recovery, so the
	 *  frontend can show the AC7 notice (a dismissible banner). Before this command,
	 *  nothing read those fields, so the notice could never reach the UI. `Ok`-only:
	 *  reading managed state never fails.
	 */
	dbRecoveryNotice: () => typedError<DbRecoveryNotice, AppErrorPayload>(__TAURI_INVOKE("db_recovery_notice")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Read the diagnostics snapshot for the Settings -> Diagnostics card.
	 * 
	 *  `Ok`-only in practice: every field is a read of managed state, a resolved
	 *  path, or a filesystem stat that reports zeroes rather than failing. It still
	 *  returns `Result` so the frontend's one `unwrap` helper covers it like every
	 *  other command.
	 */
	diagnosticsGet: () => typedError<Diagnostics, AppErrorPayload>(__TAURI_INVOKE("diagnostics_get")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Open the log directory in the OS file manager.
	 * 
	 *  Creates it first. On a launch where logging failed to start there may be no
	 *  directory at all, and opening a file manager on a path that does not exist is
	 *  an error dialog rather than an answer; an empty folder at least tells the
	 *  truth about what has been recorded.
	 */
	diagnosticsOpenLogDir: () => typedError<null, AppErrorPayload>(__TAURI_INVOKE("diagnostics_open_log_dir")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Check for an app update (E-18). Runs the plugin check and returns a typed
	 *  [`UpdateAvailability`] distinguishing "update available" / "up to date" /
	 *  "couldn't reach the update server" WITHOUT throwing (the manual button and the
	 *  on-launch check share this path). Never installs; every install is user-confirmed
	 *  via [`app_install_update`]. Infallible by design: an unreachable server (offline,
	 *  the inert private-repo endpoint, or ship-dark) is a payload state, not an error.
	 */
	appCheckForUpdate: () => __TAURI_INVOKE<UpdateAvailability>("app_check_for_update").then((v) => (({...v,error:v.error==null?v.error:({...v.error,context:v.error.context==null?v.error.context:v.error.context})}) as typeof v)),
	/**
	 *  Download, verify, and install the pending app update, then relaunch (E-18).
	 *  Called ONLY after the user confirms. The plugin verifies the minisign signature
	 *  before replacing the running binary; a verification/download failure returns a
	 *  typed [`AppError`] and leaves the current version intact. On success the process
	 *  relaunches into the new version (so this normally does not return `Ok`).
	 */
	appInstallUpdate: () => typedError<null, AppErrorPayload>(__TAURI_INVOKE("app_install_update")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  List every group with its member repo count (group-management view). */
	groupList: () => typedError<GroupSummary[], AppErrorPayload>(__TAURI_INVOKE("group_list")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Create a group. A duplicate name is rejected as an invalid setting. */
	groupCreate: (name: string, color: string | null) => typedError<GroupSummary, AppErrorPayload>(__TAURI_INVOKE("group_create", { name, color })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Rename a group without touching its color.
	 * 
	 *  Retained as a compatibility command under the E-06 additive IPC contract. New
	 *  callers should use [`group_update`], which edits name and color together in one
	 *  atomic write; this exists so a consumer on the original two-argument contract
	 *  keeps working and does not lose the group's color as a side effect.
	 */
	groupRename: (id: number, name: string) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("group_rename", { id, name })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Update a group's name and color atomically. A duplicate name is rejected; a
	 *  missing id is NotFound. A single UPDATE, so a name clash leaves both fields
	 *  unchanged - an edit never partially persists.
	 */
	groupUpdate: (id: number, name: string, color: string | null) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("group_update", { id, name, color })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Delete a group (idempotent; memberships cascade away). */
	groupDelete: (id: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("group_delete", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Assign a repo to a group (idempotent; a missing repo/group is NotFound). */
	groupAssign: (repoId: number, groupId: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("group_assign", { repoId, groupId })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  Remove a repo from a group (idempotent). */
	groupUnassign: (repoId: number, groupId: number) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("group_unassign", { repoId, groupId })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**  List the ids of the groups a repo belongs to (ascending). */
	groupsForRepo: (repoId: number) => typedError<number[], AppErrorPayload>(__TAURI_INVOKE("groups_for_repo", { repoId })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  All repo-group memberships in ONE read (BL-NI-22): one entry per repo that
	 *  belongs to at least one group, so the Repos screen builds its membership map in
	 *  a single round-trip instead of fanning `groups_for_repo` out per visible repo.
	 */
	repoGroupMemberships: () => typedError<RepoGroupMembership[], AppErrorPayload>(__TAURI_INVOKE("repo_group_memberships")).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
};

/** Events */
export const events = {
	errorRaised: makeEvent<ErrorRaised>("error:raised", (v) => ({...v,error:({...v.error,context:v.error.context==null?v.error.context:v.error.context})}), (v) => ({...v,error:({...v.error,context:v.error.context==null?v.error.context:v.error.context})})),
	navigateRequested: makeEvent<NavigateRequested>("navigate:requested"),
	notificationFired: makeEvent<NotificationFired>("notification:fired"),
	repoCheckCompleted: makeEvent<CheckCompleted>("repo:check-completed"),
	repoCheckStarted: makeEvent<CheckStarted>("repo:check-started"),
	repoMetadataRefreshed: makeEvent<MetadataRefreshed>("repo:metadata-refreshed"),
	repoStateChanged: makeEvent<StateChanged>("repo:state-changed"),
	repoUpdateCompleted: makeEvent<UpdateCompleted>("repo:update-completed"),
	repoUpdateStarted: makeEvent<UpdateStarted>("repo:update-started"),
	schedulerTick: makeEvent<SchedulerTick>("scheduler:tick"),
};

/* Types */
/**  Filter for `activity_list`. All fields optional; absent means "no constraint". */
export type ActivityFilter = {
	repoId: number | null,
	actionType: string | null,
	status: string | null,
	limit: number | null,
};

/**
 *  One row of the `activity_records` audit trail. Maps verbatim to the schema
 *  (4.2): every git/check/update operation is recorded with its raw output.
 */
export type ActivityRecord = {
	id: number,
	repoId: number,
	timestamp: number,
	actionType: string,
	status: string,
	reasonCode: string | null,
	summary: string | null,
	commitRange: string | null,
	rawCommand: string | null,
	rawStdout: string | null,
	rawStderr: string | null,
	exitCode: number | null,
	durationMs: number | null,
};

/**
 *  The on-the-wire representation of an [`AppError`]. Every error the core sends
 *  across IPC reduces to this flat shape.
 */
export type AppErrorPayload = {
	/**  Stable machine code, e.g. `fs.path_missing`. */
	code: string,
	/**  Human-readable summary of what went wrong. */
	message: string,
	/**  Actionable guidance for resolving the error. */
	remediation: string,
	/**  Variant-specific detail (path, exit_code, stderr, cause, ...). */
	context: unknown | null,
};

/**  Which branches a repo is allowed to update. */
export type BranchPolicy = "default_branch_only" | "tracked_upstream_only" | "approved_branches" | "any_branch";

/**
 *  Typed "check completed" event, broadcast after every `repo_check_now`.
 * 
 *  The wire name is pinned to `repo:check-completed` (the E-06 contract);
 *  without the explicit `event_name` the derive would emit `check-completed`
 *  from the struct identifier. The frontend listens via the generated
 *  `events.checkCompleted` binding, never a raw string.
 */
export type CheckCompleted = CheckCompletedPayload;

/**  Event payload emitted when a check completes (the slimmer broadcast form). */
export type CheckCompletedPayload = {
	repoId: number,
	decision: string,
	ahead: number | null,
	behind: number | null,
	checkedAt: number,
	/**
	 *  The typed reason, when there is one, so a window that did not initiate the
	 *  check learns WHY it ended that way rather than only that it ended.
	 */
	reason: string | null,
	/**
	 *  Whether the check failed operationally. See [`CheckResult::failed`].
	 * 
	 *  Before BL-NI-04 this payload could not carry either field for the simple
	 *  reason that it was never emitted for a failure at all: the command
	 *  short-circuited on the error first.
	 */
	failed: boolean,
};

/**  Result of a "check now" run, returned to the caller. */
export type CheckResult = {
	repoId: number,
	decision: string,
	reason: string | null,
	ahead: number | null,
	behind: number | null,
	isDirty: boolean,
	isDetached: boolean,
	checkedAt: number,
	/**
	 *  Whether the check FAILED operationally, as opposed to completing with a
	 *  policy skip (BL-NI-04).
	 * 
	 *  Additive, and it exists so no consumer has to re-derive the distinction.
	 *  A failed fetch and a deliberate skip both arrive as
	 *  `decision == "skip-with-reason"`, and they must not read the same to a
	 *  user: "skipped, working tree is dirty" is the safety rule doing its job,
	 *  while "could not reach the remote" is a problem. Telling them apart from
	 *  `reason` alone means matching the operational reason codes as strings,
	 *  which is a classification the backend already performs and which a second
	 *  copy in TypeScript could only drift from.
	 * 
	 *  `true` for an auth, network, or otherwise non-zero fetch. `false` for
	 *  every policy decision, including every skip.
	 */
	failed: boolean,
};

/**  Typed `repo:check-started` event (a check began for a repo). */
export type CheckStarted = CheckStartedPayload;

/**  Payload for the `repo:check-started` event. */
export type CheckStartedPayload = {
	repoId: number,
};

/**
 *  A daily roll-up of repo activity.
 * 
 *  E-11 (summaries) owns field authority for this type; any change here is
 *  additive (new fields/buckets), never a rename or removal, so the binding and
 *  downstream consumers stay stable.
 */
export type DailySummary = {
	date: string,
	updatedCount: number,
	releasesCount: number,
	attentionCount: number,
	noChangeCount: number,
	updated: SummaryItem[],
	newReleases: SummaryItem[],
	attention: SummaryItem[],
};

/**
 *  The one-time database-recovery notice (E-02 AC7 / BL-NI-33).
 * 
 *  When the startup migration failed and the old database had to be moved aside,
 *  `recovered` is true and `backup_path` is where the previous database was
 *  preserved (a display string). The frontend reads this once at launch (the
 *  `db_recovery_notice` command) to surface a dismissible banner. On a normal
 *  launch `recovered` is false and `backup_path` is `None`. Before this type
 *  existed the parked `db_recovered` / `db_backup_path` fields had no reader, so
 *  the AC7 notice could never reach the UI.
 */
export type DbRecoveryNotice = {
	recovered: boolean,
	backupPath: string | null,
};

/**
 *  A read-only snapshot of where RepoSync keeps its files and how it is
 *  currently configured, for the Settings -> Diagnostics card.
 * 
 *  Every field is DERIVED, not stored: this is a view over the resolved paths,
 *  the logging configuration actually installed at startup, the live git probe,
 *  and the since-launch scheduler counters. Nothing here is settable, which is
 *  why it has no write counterpart.
 * 
 *  Paths are rendered strings rather than structured values because their only
 *  consumer is a label the user reads or copies into a bug report. Note that on
 *  Windows they contain the account name; the card says so next to the copy
 *  action rather than mangling the paths, since a redacted path is useless for
 *  the thing a user opens this card to do - find the folder.
 */
export type Diagnostics = {
	/**  The running app version (the crate version baked in at build time). */
	appVersion: string,
	/**  The resolved app-data directory. */
	dataDir: string,
	/**  The SQLite database file inside it. */
	dbPath: string,
	/**  The rolling-log directory. */
	logDir: string,
	/**
	 *  Whether the logging subscriber was installed successfully AT STARTUP.
	 * 
	 *  Deliberately named for what it proves. `tracing_appender` writes on a
	 *  background worker thread and exposes no error channel, so a disk that
	 *  fills or an ACL that changes AFTER startup produces no signal here: this
	 *  stays `true` while nothing reaches disk. Pair it with `log_dir_readable`
	 *  and `log_file_count`, which are measured live - "started, but the
	 *  directory has no files in it" is the observable contradiction, and the
	 *  UI flags exactly that. Durable write-failure telemetry is BL-NI-63.
	 */
	loggingActive: boolean,
	/**  The effective maximum level, e.g. `"INFO"`. `None` when logging is off. */
	logLevel: string | null,
	/**  Daily files retained (the AGE half of retention). `None` when logging is off. */
	logMaxFiles: number | null,
	/**  The directory size budget in bytes (the SIZE half). `None` when off. */
	logMaxBytes: number | null,
	/**
	 *  Whether the log directory could be read at all. `false` is a distinct,
	 *  worse state than "readable and empty": a directory the app cannot read
	 *  is one it most likely cannot write to either. The counts below mean
	 *  nothing when this is `false`.
	 */
	logDirReadable: boolean,
	/**  Log files present right now (measured, not remembered). */
	logFileCount: number,
	/**  Bytes those files occupy right now. */
	logBytes: number,
	/**
	 *  Whether the data directory sits under a OneDrive-synced tree, where a sync
	 *  agent can corrupt the SQLite WAL sidecars mid-write (BL-NI-12).
	 */
	onedriveRooted: boolean,
	/**  The resolved `git` executable, or `None` when none was found. */
	gitPath: string | null,
	/**  The probed git version, or `None` when git is unavailable. */
	gitVersion: string | null,
	/**
	 *  Whether a git executable was resolved at all. `false` is the only state
	 *  in which RepoSync will not run git.
	 */
	gitResolved: boolean,
	/**
	 *  Whether the resolved git is at or above the supported >= 2.30 floor.
	 * 
	 *  Split from `git_resolved` rather than folded into one "available" flag,
	 *  because [`crate::git::GitAvailability`] has THREE states and a single
	 *  boolean can only carry two. A below-floor git is explicitly "usable but
	 *  flagged - operations are still attempted" (E-03 AC7), so collapsing it
	 *  into "not available" would tell a user reading this panel that RepoSync
	 *  has stopped running git when it has not.
	 */
	gitMeetsFloor: boolean,
	/**  Scheduler cycles completed since launch. */
	schedulerCycles: number,
	/**  Repos run across those cycles. */
	schedulerReposChecked: number,
	/**
	 *  Jobs that ran but could not persist their outcome (BL-NI-14). Non-zero
	 *  means some checks silently retried; the log carries the reason under
	 *  `scheduler.outcome_persist_failed`.
	 */
	schedulerOutcomePersistFailures: number,
	/**
	 *  Whether the startup migration failed and the previous database was moved
	 *  aside (E-02 AC7).
	 */
	dbRecovered: boolean,
};

/**  What to do when the working tree is dirty at update time. */
export type DirtyHandling = "skip" | "warn_and_block" | "auto_stash" | "fetch_only_when_dirty";

/**
 *  Typed `error:raised` event (a backend error reached the global surface).
 * 
 *  DEVIATION from the other six events' `pub struct X(pub Payload)` newtype
 *  shape, forced by a tauri-specta rc.25 codegen defect. This is the only event
 *  whose payload transitively carries the `serde_json::Value` field
 *  (`AppErrorPayload.context`) that the builder's semantic remap rewrites to
 *  `unknown`. That remap makes tauri-specta emit a runtime payload transform for
 *  the event. For a tuple newtype `ErrorRaised(Payload)`, tauri-specta rc.25
 *  walks the newtype body as an unnamed-field struct and indexes the payload as
 *  `v[0]`, while the generated TS type (correctly) collapses the newtype to the
 *  inner object - so the `v[0]`-indexing transform does not typecheck (verified:
 *  `#[serde(transparent)]` / `#[specta(transparent)]` does NOT help, because
 *  specta still emits a single unnamed-field struct DataType). Declaring the
 *  event as a NAMED single-field struct makes the transform walk the field by
 *  name (`v.error...`) instead, which typechecks.
 * 
 *  The wire shape is unchanged: a tuple newtype of `{ error: AppErrorPayload }`
 *  and this named struct both serialize to `{ "error": { ...AppErrorPayload } }`,
 *  so the frontend contract is identical. The generated TS `ErrorRaised` is
 *  `{ error: AppErrorPayload }`.
 */
export type ErrorRaised = {
	error: AppErrorPayload,
};

/**
 *  A repo group (tag) with its current member count. A flattened read of
 *  `groups` + a COUNT of `repo_groups` memberships, for the group-management view.
 */
export type GroupSummary = {
	id: number,
	name: string,
	color: string | null,
	repoCount: number,
};

/**
 *  Typed `repo:metadata-refreshed` event (E-17 finding 3): emitted once per background
 *  GitHub metadata refresh pass that changed at least one repo, so the aggregate list
 *  view refetches exactly once. Additive E-06 amendment (was a flagged V1.1 surface in
 *  the E-17 spec; promoted to V1 to fix the background-refresh-invisible finding).
 */
export type MetadataRefreshed = MetadataRefreshedPayload;

/**
 *  Payload for the `repo:metadata-refreshed` event (E-17 finding 3): the background
 *  GitHub metadata + branch/PR refresh pass wrote fresh data for one or more repos.
 * 
 *  The shell emits this ONCE per pass (only when at least one repo actually changed),
 *  so the aggregate list view (dashboard, repos) refetches EXACTLY ONCE per pass -
 *  never an N+1 refetch storm (the Phase-3 F3 batching discipline). It is deliberately
 *  distinct from `scheduler:tick`: a metadata refresh is not a git check, so reusing
 *  the tick would falsely imply a check ran. `changed_count` is how many repos moved
 *  this pass; `at` is the pass's unix-second timestamp. Per-repo `repo:state-changed`
 *  events (one per changed repo) drive the focused drawer separately.
 */
export type MetadataRefreshedPayload = {
	changedCount: number,
	at: number,
};

/**
 *  Typed `navigate:requested` event (E-13 tray): the shell asks the UI to switch
 *  views.
 * 
 *  Emitted by the tray "Settings" item so it can open + focus the window ON the
 *  settings view; the frontend app-shell listens (`events.navigateRequested`) and
 *  routes to the named target.
 */
export type NavigateRequested = NavigateRequestedPayload;

/**
 *  Payload for the `navigate:requested` event (E-13 tray): the shell asks the
 *  frontend to switch to a named view. `target` is a view id the app-shell router understands
 *  (`"dashboard"` / `"repos"` / `"activity"` / `"settings"`); an unknown target is
 *  ignored by the frontend. Used by the tray "Settings" item to open + focus the
 *  window on the settings view.
 */
export type NavigateRequestedPayload = {
	target: string,
};

/**  Typed `notification:fired` event (a desktop notification was raised). */
export type NotificationFired = NotificationFiredPayload;

/**  Payload for the `notification:fired` event. */
export type NotificationFiredPayload = {
	kind: string,
	repoId: number | null,
	title: string,
	body: string,
};

/**
 *  The full detail of a tracked repo (detail view). Repeats every
 *  [`RepoSummary`] field verbatim (NOT `serde(flatten)` - it is fragile with
 *  specta rc.25) and adds the rest of `repos` + `repo_local_state` +
 *  `repo_remote_meta`.
 */
export type RepoDetail = {
	id: number,
	localName: string,
	hostType: string,
	aheadCount: number | null,
	behindCount: number | null,
	isDirty: boolean,
	isDetached: boolean,
	enabled: boolean,
	autoPaused: boolean,
	lastCheckedAt: number | null,
	lastErrorCode: string | null,
	latestReleaseTag: string | null,
	localPath: string,
	remoteOriginUrl: string | null,
	defaultBranch: string | null,
	updateMode: string,
	checkFrequencyMin: number,
	createdAt: number,
	notes: string | null,
	activeBranch: string | null,
	headSha: string | null,
	upstreamBranch: string | null,
	lastLocalCommitAt: number | null,
	lastUpdatedAt: number | null,
	lastAttemptedAt: number | null,
	nextCheckAt: number | null,
	consecutiveFailures: number,
	description: string | null,
	topicsJson: string | null,
	latestReleaseAt: number | null,
	latestReleaseUrl: string | null,
	isArchived: boolean,
	lastRemoteSha: string | null,
	lastFetchedAt: number | null,
	/**
	 *  Open pull-request count. `None` = un-refreshed / non-GitHub / unknown (a
	 *  404-or-403 on a private repo preserves the cache; it is NEVER a fabricated 0).
	 */
	openPrCount: number | null,
	/**  Open pull requests targeting the default branch (a subset of `open_pr_count`). */
	defaultBranchPrCount: number | null,
	/**
	 *  When the PR counts were last confirmed against GitHub, for the drawer's
	 *  "as of <time>" staleness marker when offline / rate-limited (E-17 AC8).
	 */
	prLastCheckedAt: number | null,
};

/**  Filter for `repo_list`. All fields optional; absent means "no constraint". */
export type RepoFilter = {
	enabledOnly: boolean | null,
	hostType: string | null,
	query: string | null,
};

/**
 *  One repo's group memberships: the repo id and the ascending, de-duplicated ids
 *  of the groups it belongs to. The bulk read (`repo_group_memberships`) returns
 *  one of these per repo that has at least one membership, so the Repos screen can
 *  build its `repoId -> groupId[]` map in a SINGLE IPC round-trip instead of
 *  fanning `groups_for_repo` out per visible repo (BL-NI-22). A repo with no
 *  memberships is simply absent from the list.
 */
export type RepoGroupMembership = {
	repoId: number,
	groupIds: number[],
};

/**  Stable identifier for a tracked repo (its `repos.id`). */
export type RepoId = number;

/**
 *  The at-a-glance form of a tracked repo (list view). A flattened join of
 *  `repos` + `repo_local_state` + the latest release tag.
 */
export type RepoSummary = {
	id: number,
	localName: string,
	hostType: string,
	aheadCount: number | null,
	behindCount: number | null,
	isDirty: boolean,
	isDetached: boolean,
	enabled: boolean,
	autoPaused: boolean,
	lastCheckedAt: number | null,
	lastErrorCode: string | null,
	latestReleaseTag: string | null,
	/**
	 *  Open pull-request count (E-17). `None` = un-refreshed or non-GitHub repo (a
	 *  clean unknown, never a fabricated zero). Rides the single `repo_list` join.
	 */
	openPrCount: number | null,
	/**
	 *  The HEAD commit's committer time (E-17), distinct from `last_checked_at`
	 *  ("when RepoSync last looked"). `None` when the inspect never read it.
	 */
	lastLocalCommitAt: number | null,
};

/**  A candidate repository found while scanning a parent folder. */
export type ScanCandidate = {
	localPath: string,
	localName: string,
	alreadyTracked: boolean,
	remoteOriginUrl: string | null,
};

/**  The result of scanning a parent folder for git repositories. */
export type ScanResult = {
	parentPath: string,
	discovered: ScanCandidate[],
};

/**  Typed `scheduler:tick` event (the scheduler ran a cycle). */
export type SchedulerTick = SchedulerTickPayload;

/**  Payload for the `scheduler:tick` event. */
export type SchedulerTickPayload = {
	checked: number,
	due: number,
	at: number,
};

/**
 *  The singleton `settings` row. `github_token_present` is a derived boolean -
 *  the token itself lives in the OS keychain, never on the wire.
 */
export type Settings = {
	globalCheckMinutes: number,
	quietHoursStart: number | null,
	quietHoursEnd: number | null,
	notifyOnRelease: boolean,
	notifyOnFailure: boolean,
	gitExecutablePath: string | null,
	editorCommand: string | null,
	terminalCommand: string | null,
	autostart: boolean,
	activityRetentionD: number,
	githubTokenPresent: boolean,
	/**
	 *  Whether RepoSync checks for an app update on launch (E-18). Default `true`.
	 *  This gates ONLY the on-launch check; the manual "Check for updates" action
	 *  runs regardless, and no update ever installs without the user confirming.
	 *  Provisional-additive per E-06's additive-revision rule; mirrors the
	 *  `settings.auto_update_check` column added in migration `0006_auto_update.sql`.
	 */
	autoUpdateCheck: boolean,
	/**
	 *  Whether the window's close (X) button HIDES the app to the tray (`true`,
	 *  the default and prior hardcoded behavior) or QUITS it (`false`). Read live
	 *  by the close handler via a mirrored `AtomicBool` in the shell's AppState.
	 *  Mirrors the `settings.close_minimizes_to_tray` column added in migration
	 *  `0007_close_minimizes_to_tray.sql`.
	 */
	closeMinimizesToTray: boolean,
};

/**  Typed `repo:state-changed` event (a repo's cached state was updated). */
export type StateChanged = StateChangedPayload;

/**  Payload for the `repo:state-changed` event. */
export type StateChangedPayload = {
	repoId: number,
	lastErrorCode: string | null,
};

/**  One repo's line in a summary bucket (updated / new release / attention). */
export type SummaryItem = {
	repoId: number,
	localName: string,
	detail: string | null,
};

/**
 *  The result of an app self-update availability check (E-18 auto-update).
 * 
 *  Returned by the `app_check_for_update` command (a thin wrapper over the Tauri
 *  updater plugin, so the on-launch check and the Settings button share one typed
 *  path). The three UI states are distinguished WITHOUT throwing: an update is
 *  available (`available == true`, `new_version`/`notes` set), the app is up to
 *  date (`available == false`, `error == None`), or the update server could not be
 *  reached (`available == false`, `error == Some`) - the last case also covers the
 *  inert private-repo endpoint (a 404 while the repo is private) and the ship-dark
 *  state (no production signing key configured yet), both rendered as "could not
 *  reach the update server." `current_version` is always the running app version,
 *  so the Settings "Updates" section can show it. Tauri-free: `error` reuses the
 *  frozen [`AppErrorPayload`] wire shape, never a `tauri` type.
 */
export type UpdateAvailability = {
	currentVersion: string,
	available: boolean,
	newVersion: string | null,
	notes: string | null,
	error: AppErrorPayload | null,
};

/**  Typed `repo:update-completed` event (an update finished for a repo). */
export type UpdateCompleted = UpdateCompletedPayload;

/**  Payload for the `repo:update-completed` event. */
export type UpdateCompletedPayload = {
	repoId: number,
	outcome: string,
};

/**
 *  How a repo is updated. snake_case on the wire to match the `update_mode`
 *  column values.
 */
export type UpdateMode = "check_only" | "fetch_only" | "pull_ff_only" | "pull_standard" | "pull_rebase";

/**  The full per-repo update policy (E-07). */
export type UpdatePolicy = {
	mode: UpdateMode,
	dirtyHandling: DirtyHandling,
	branchPolicy: BranchPolicy,
};

/**  The outcome of an "update now" run for a single repo. */
export type UpdateResult = {
	repoId: number,
	mode: string,
	outcome: string,
	commitRange: string | null,
	ahead: number | null,
	behind: number | null,
	updatedAt: number,
};

/**  Typed `repo:update-started` event (an update began for a repo). */
export type UpdateStarted = UpdateStartedPayload;

/**  Payload for the `repo:update-started` event. */
export type UpdateStartedPayload = {
	repoId: number,
	mode: string,
};

/**  A weekly roll-up: a window of [`DailySummary`] days. V1.1 stub (E-11 / V1.1). */
export type WeeklySummary = {
	weekStart: string,
	days: DailySummary[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

