/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Add a repository to the registry by absolute local path.
	 * 
	 *  Thin wrapper over [`reposync_core::repo::add`]: validates + inspects + writes
	 *  the `repos` / `repo_local_state` rows and returns the new [`RepoId`].
	 */
	repoAddPath: (path: string) => typedError<RepoId, AppErrorPayload>(__TAURI_INVOKE("repo_add_path", { path })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
	/**
	 *  Run a "check now" for a tracked repo, then broadcast the result.
	 * 
	 *  Calls [`reposync_core::repo::check_now`], emits the `repo:check-completed`
	 *  event so every window's listener sees the outcome, and returns the full
	 *  [`CheckResult`] to the caller.
	 */
	repoCheckNow: (id: number) => typedError<CheckResult, AppErrorPayload>(__TAURI_INVOKE("repo_check_now", { id })).then((v) => ((v.status === "error" ? { ...v, error: ({...v.error,context:v.error.context==null?v.error.context:v.error.context}) } : v) as typeof v)),
};

/** Events */
export const events = {
	repoCheckCompleted: makeEvent<CheckCompleted>("repo:check-completed"),
};

/* Types */
/**
 *  The on-the-wire representation of an [`AppError`]. Every error the core sends
 *  across IPC reduces to this flat shape.
 */
export type AppErrorPayload = {
	/**  Stable machine code, e.g. `fs.path_missing`. */
	code: string,
	/**  Human-readable summary of what went wrong. */
	message: string,
	/**  Actionable guidance for resolving the error. */
	remediation: string,
	/**  Variant-specific detail (path, exit_code, stderr, cause, ...). */
	context: unknown | null,
};

/**
 *  Typed "check completed" event, broadcast after every `repo_check_now`.
 * 
 *  The wire name is pinned to `repo:check-completed` (the E-06 contract);
 *  without the explicit `event_name` the derive would emit `check-completed`
 *  from the struct identifier. The frontend listens via the generated
 *  `events.checkCompleted` binding, never a raw string.
 */
export type CheckCompleted = CheckCompletedPayload;

/**  Event payload emitted when a check completes (the slimmer broadcast form). */
export type CheckCompletedPayload = {
	repoId: number,
	decision: string,
	ahead: number | null,
	behind: number | null,
	checkedAt: number,
};

/**  Result of a "check now" run, returned to the caller. */
export type CheckResult = {
	repoId: number,
	decision: string,
	reason: string | null,
	ahead: number | null,
	behind: number | null,
	isDirty: boolean,
	isDetached: boolean,
	checkedAt: number,
};

/**  Stable identifier for a tracked repo (its `repos.id`). */
export type RepoId = number;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

